#!/bin/bash

ORANGE=$'\e[38;05;202m'
BOLD=$'\e[1m'
R=$'\e[0m'

ACTION=$1
shift

declare -A funcs
funcs[test]=testf;
funcs[update]=update;

testf() {
	echo "I'm the testf function"
}

update() {
	echo "Reloading ${ORANGE}${BOLD}.dotfiles${R}"
	source ../.dotfiles
}

${funcs[${ACTION}]}
