#!/bin/bash

ORANGE=$'\e[38;05;202m'
BOLD=$'\e[1m'
R=$'\e[0m'

if ! [ -n "$1" ]; then
	cd $DOTFILES;
	return;
fi

ACTION=$1
shift

declare -A funcs
funcs[test]=testf;
funcs[update]=update;
funcs[upgrade]=upgrade;
funcs[setup]=setup;

testf() {
	echo "I'm the testf function"
}

update() {
	echo "Reloading ${ORANGE}${BOLD}.dotfiles${R}"
	source ${DOTFILES}/.dotfiles
}

upgrade() {
	echo "${ORANGE}${BOLD}Pulling repository...${R}"
	odir=$(pwd)
	cd ${DOTFILES}
	git pull origin master
	update
	cd ${odir}
}

setup() {
	DOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
	
	# GIT
	echo "Create .gitconfig symlink"
	#ln -s ${DOTFILES}/.gitconfig ~/.gitconfig
	
	# VIM
	echo "Create .vimrc symlink"
	#ln -s ${DOTFILES}/.vimrc ~/.vimrc

	# Sublime
	echo "Create Sublime Text preferences symlink"
	sublDir=~/.config/sublime-text-3/Packages/User
	mkdir -p $sublDir
	ln -s ${DOTFILES}/config/Preferences.sublime-settings ${sublDir}/Preferences.sublime-settings
	
	#echo -e "\n\n#Added by .dotfiles setup script\nsource $DOTFILES/.dotfiles" >> ~/.bashrc
}

fixkeyboadrd() {
	ibus-daemon -rd
}

${funcs[${ACTION}]}