#!/bin/bash
MATERIAL_DIR=$DOTFILES/data/material-design-icons

_getDirectories () {
	local word=${COMP_WORDS[COMP_CWORD]}
	echo word;
    local line=${COMP_LINE}
    echo line;
    local xpat='!*.*'

    COMPREPLY=($(compgen -f -X "$xpat" -- "${word}"))
}