#!/bin/bash
function usage {
  echo -e "Usage:\n\t$ `basename $0` [database] [user]"
}

if [[ $# -eq 1 ]]
then
  usage
  exit 65
fi

if [[ $# -eq 2 ]]
then
  database=$1
  user=$2
else
  read -p "Enter a database name: " database
  read -p "Enter a username: " user

fi

read -s -p "Enter password for $user: " userpw
echo ""

Q1="CREATE DATABASE IF NOT EXISTS $database;"
Q2="GRANT USAGE ON *.* TO $user@localhost IDENTIFIED BY '$userpw';"
Q3="GRANT ALL PRIVILEGES ON $database.* TO $user@localhost;"
Q4="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}${Q4}"

mysql -u root -p -e "$SQL"
echo "Created database \"$database\" for user \"$user\""