#!/bin/bash
function usage {
  echo -e "Usage:\n\t$ `basename $0` [database] [user]"
}

if [[ $# -ne 2 ]]
then
  usage
  exit 65
fi

read -s -p "Enter password for $2: " userpw
echo ""

Q1="CREATE DATABASE IF NOT EXISTS $1;"
Q2="GRANT USAGE ON *.* TO $2@localhost IDENTIFIED BY '$userpw';"
Q3="GRANT ALL PRIVILEGES ON $1.* TO $2@localhost;"
Q4="FLUSH PRIVILEGES;"
SQL="${Q1}${Q2}${Q3}${Q4}"

mysql -u root -p -e "$SQL"
echo "Created database \"$1\" for user \"$2\""