#!/usr/bin/env bash

config=$1

if [ -z ${config} ]; then
	echo "Usage: `basename $0` </path/to/mysql-s3.backup.env>"
	echo ""
	echo "Structure of config file"
	cat data/mysql-s3-backup.sample.env
	exit 1
fi

function startBackup
{
    local baseDir=/tmp/mysql-s3-backup/
    local dateStr=$(date +"%Y-%m-%d_%H-%M-%S%z")
    local dirName=${DIR_PREFIX}-${dateStr}
    local dir="${baseDir}${dirName}"
    mkdir -p ${dir}
    cd ${dir}
    # Delete files older than 10 days
    find ${baseDir}* -mtime +10 -exec rm {} \;

    local sqlAuth="-u ${MYSQL_USER} -p${MYSQL_PASSWORD}"

    databases=`echo 'show databases;' | mysql ${sqlAuth} | tail -n +2 | grep -v _schema | grep -v mysql | grep -v sys`
    for database in ${databases}
    do
        mysqldump ${sqlAuth} --databases ${database} --no-create-db --single-transaction > "${database}.sql"
    done

    local tarFile=${dirName}.tar.gz

    tar -zcvf ../${tarFile} *
    cd ..
    rm -rf ${dirName}
    aws s3 cp ${tarFile} s3://${S3_BUCKET}/backups/
    rm ${tarFile}
}

source ${config};
startBackup


